import Head from 'next/head';

export default function Home() {
  return (
    <div className='antialiased'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <h1 className='text-2xl font-semibold'>header</h1>
      </main>

      <footer></footer>
    </div>
  );
}
